### ISSUE TITLE
How to generate `REPL_IDENTITY_KEY`

### ISSUE THREAD

**Issue by INF800** [replit/replit-ai-python#40]
Error:

```
MissingEnvironmentVariable: Did not find the environment variable: REPL_IDENTITY_KEY
```

Background:

Need it for https://github.com/run-llama/llama_index/issues/10359

**Comment by INF800** [comment]
Looks like I'll need other keys `REPL_IDENTITY_KEY`, `REPL_IDENTITY` & `REPL_ID`.

**Comment by INF800** [comment]
Hmm, I see that they live inside repl env. But cannot use them in third partly env like local or colab.

Even if we get to use them. need a paying account for it. Leads to #30 (reproduced @ https://replit.com/@rakesh4real/non-paying-account)

```shell
Traceback (most recent call last):
  File "/home/runner/non-paying-account/main.py", line 14, in <module>
    response = model.complete(["Write a tweet about the meaning of life: "],
  File "/home/runner/non-paying-account/.pythonlibs/lib/python3.10/site-packages/replit/ai/modelfarm/completion_model.py", line 51, in complete
    self._check_response(response)
  File "/home/runner/non-paying-account/.pythonlibs/lib/python3.10/site-packages/replit/ai/modelfarm/model.py", line 57, in _check_response
    raise InvalidResponseException(rjson["detail"])
replit.ai.modelfarm.exceptions.InvalidResponseException: Non-paying account.
```
